#!/usr/bin/env python
#encoding:utf-8
list = [1,2,3,2,12,3,1,3,21,2,2,3,4111,22,3333,444,111,4,5,777,65555,45,33,45]

num1 = 0
num2 = 0

for i in list:
   if num1 < i:
      num1 = i


for i in list:
   if i == num1:
       continue
   elif num2 < i:
       num2 = i

print num1,num2
